#!/bin/sh
### BEGIN INIT INFO
# Provides:		whoshome
# Required-Start:	$all
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Software for picture frame scanner
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

DAEMON=/home/pi/whoshome/whoshome.py
PIDFILE=/var/run/whoshome.pid

do_start() {
	log_daemon_msg "Startnig whoshome service"
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --startas $DAEMON
	log_end_msg $?
}

do_stop() {
	log_daemon_msg "Stopping whoshome service"
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
	log_end_msg $?
}

case $1 in
	start|stop)
		do_${1}
		;;
	restart|reload|force-reload)
		do_stop
		do_start
		;;
	status)
		status_of_proc "whoshome" "$DAEMON" && exit 0 || exit $?
		;;
	*)
		echo "usage: /etc/init.d/whoshome {start|stop}"
		exit 1
		;;
esac
exit 0
